### PR TITLE
Let's try adding an entry

### PR DESCRIPTION
**Pull request by maelvls**
I want to "feel" what the workflow would be like.

### CODE REVIEW

**Comment by SgtCoDFish** [comment]
```yaml
mael: does it work?
```

It does work :)

**Comment by maelvls** [comment]
I pulled the latest commit from master (3730a3f0f2a02f4f1855c2a44e6b48f2b25bfd11) and ran

```sh
make open
```

For some reason, I got the following error:
```
SOPS_AGE_KEY_FILE=/home/mvalais/code/jetstack/soperationalize/private-keys/managed-secret-key.txt bin/sops secrets.yaml
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  056A3410756CCC1E6664FEDA78286B84F25BC9E6: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /home/mvalais/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2

  F105E2358FEBFC3DA4A4949900758A3D27F4C016: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /home/mvalais/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2

  E8D89217070A53474071163AE0C3750AD0EDAF32: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /home/mvalais/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2

  0D1D34C44EA8DFCAF3133866F38ACBFD9F0CF8B5: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /home/mvalais/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2

  1EA51A00ABC3A5C16E43E7B0DD14CC017E32BEB1: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /home/mvalais/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2

  age1z9568c9f4q79lplxsr0tdu07wwhesnagpnt8re6xl3ds5lh9rq5qwuamrw: FAILED
    - | failed to open file: open
      | /home/mvalais/code/jetstack/soperationalize/private-keys/managed-secret-key.txt:
      | no such file or directory

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
make: *** [Makefile:25: open] Error 128
```

Then I immediately re-run `make open` and this time it worked. The first time, I wasn't prompted my GPG passphrase. The second time, I was prompted (although I had checked the "save passphrase in keyring").

**Comment by SgtCoDFish** [comment]
Not sure what happened there! This is the relevant one, where it failed to open your actual keyring:

```text
  F105E2358FEBFC3DA4A4949900758A3D27F4C016: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /home/mvalais/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2
```

GPG is such an unusually-designed piece of software that it's pretty hard to know what might've gone wrong there unfortunately; I suspect if we all used `age` keys it'd be easier to debug!

**Comment by maelvls** [comment]
What is the reason keeping us from using `age` instead of `gpg`?

Is it because GitHub doesn't support/serve `age` public keys?

**Comment by SgtCoDFish** [comment]
With this tool there's nothing stopping us; you can run

```bash
make GH_USERNAME="maelvls" append-age-managed-key
make updatekeys
```

That'll generate an age key locally and use it to encrypt the file, ready for a PR. More details in the readme

I couldn't do it automatically like with PGP because like you said there's no place that I can download pre-generated age keys.

**Comment by maelvls** [comment]
What do you think is the next step?

I am very much in favour of using this instead of the Jetstack-specific 1password/hashicorp vault.

**Comment by SgtCoDFish** [comment]
First of all: Thank you so much for engaging, asking questions and responding, it really makes me feel like the things I do are worth it to have this kind of discussion and I needed that today! :bow: 

I guess the next step is that I raise a PR against cert-manager/infrastructure to add this there, it goes through a more formal review loop and we start moving secrets across? Does that sound good?

**Comment by maelvls** [comment]
Yes, let's start with cert-manager/infrastructure. We could raise this topic during the next biweekly dev meeting.

**Pull request merged**
